const CASH = "CASH";
const ONLINE = "ONLINE";
const UPI = "UPI";
const CARD = "CARD";
const WALLET = "WALLET";
const NET_BANKING = "NET_BANKING";
const EMI = "EMI";
const PAY_LATER = "PAY_LATER";
const BANK_TRANSFER = "BANK_TRANSFER";
const CHEQUE = "CHEQUE";
const DEMAND_DRAFT = "DEMAND_DRAFT";

export const PAYMENT_TYPES = [
    CASH,
    ONLINE,
    UPI,
    CARD,
    WALLET,
    NET_BANKING,
    EMI,
    PAY_LATER,
    BANK_TRANSFER,
    CHEQUE,
    DEMAND_DRAFT
];

export {
    BANK_TRANSFER, CARD, CASH, CHEQUE,
    DEMAND_DRAFT, EMI, NET_BANKING, ONLINE, PAY_LATER, UPI, WALLET
};

